#!/bin/tcsh
#
set dst=$HOME/pub/csweb/software/utf8conditioner

make clean
echo "Copying to $dst..."
rsync --exclude=CVS --exclude="*~" --exclude=copyToCsweb --delete -rav ./ $dst/

echo "Now publishing to web..."
publish-csweb.pl software/utf8conditioner


